name: Terraform Apply for SIT

on:
  workflow_dispatch:  # This allows manual triggering

jobs:
  terraform:
    name: Terraform Apply to SIT
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    environment:
      name: sit  # Set to 'sit' to identify the GitHub environment .

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_SIT_ROLE_ARN }}  # IAM Role ARN for SIT (ensure this is stored as a secret)
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Terraform Init
        run: |
          cd env/sit  # Navigate to the 'sit' environment directory
          terraform init

      - name: Terraform Plan
        run: |
          cd env/sit  # Navigate to the 'sit' environment directory
          terraform plan -var-file=sit.tfvars

      - name: Terraform Apply
        run: |
          cd env/sit  # Navigate to the 'sit' environment directory
          terraform apply -var-file=sit.tfvars -auto-approve
