name: Orchestrate SIT and Prod Deployments

on:
  workflow_run:
    workflows: ["deployment-dev.yml"]
    types: [completed]

permissions:
  contents: read
  actions: write

jobs:
  deploy-sit:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Trigger SIT Workflow
        uses: actions/github-script@v6
        with:
          script: |
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deployment-sit.yml',
              ref: 'main'
            });

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-sit
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Trigger Prod Workflow
        uses: actions/github-script@v6
        with:
          script: |
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deployment-prod.yml',
              ref: 'main'
            });
